# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-14

    env:
      XCODE_VERSION: 15.3
      ZIP_PKG_NAME_IOS: "WebDriverAgentRunner-Runner.zip"
      PKG_PATH_IOS: "appium_wda_ios"
      ZIP_PKG_NAME_TVOS: "WebDriverAgentRunner_tvOS-Runner.zip"
      PKG_PATH_TVOS: "appium_wda_tvos"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "${{ env.XCODE_VERSION }}"
    - run: npm install --no-package-lock
      name: Install dev dependencies
    - run: npm run build
      name: Run build
    - run: npm run test
      name: Run test

    # building WDA packages
    - name: Build iOS
      run: |
        xcodebuild clean build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -derivedDataPath $PKG_PATH_IOS \
          -scheme WebDriverAgentRunner \
          -destination generic/platform=iOS \
          CODE_SIGNING_ALLOWED=NO ARCHS=arm64
    - name: Creating a zip of WebDriverAgentRunner-Runner.app for iOS after removing test frameworks
      run: |
        pushd appium_wda_ios/Build/Products/Debug-iphoneos
        rm -rf WebDriverAgentRunner-Runner.app/Frameworks/XC*.framework
        zip -r $ZIP_PKG_NAME_IOS WebDriverAgentRunner-Runner.app
        popd
        mv $PKG_PATH_IOS/Build/Products/Debug-iphoneos/$ZIP_PKG_NAME_IOS ./
    - name: Build tvOS
      run: |
        xcodebuild clean build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -derivedDataPath $PKG_PATH_TVOS \
          -scheme WebDriverAgentRunner_tvOS \
          -destination generic/platform=tvOS \
          CODE_SIGNING_ALLOWED=NO ARCHS=arm64
    - name: Creating a zip of WebDriverAgentRunner-Runner.app for tvOS after removing test frameworks
      run: |
        pushd appium_wda_tvos/Build/Products/Debug-appletvos
        rm -rf WebDriverAgentRunner_tvOS-Runner.app/Frameworks/XC*.framework
        zip -r $ZIP_PKG_NAME_TVOS WebDriverAgentRunner_tvOS-Runner.app
        popd
        mv $PKG_PATH_TVOS/Build/Products/Debug-appletvos/$ZIP_PKG_NAME_TVOS ./

    # release tasks
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      name: Release

